<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOhXnBO3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOhXnBO3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOhXnBO3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOhXnBO3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOhXnBO3\App_KernelDevDebugContainer([
    'container.build_hash' => 'OhXnBO3',
    'container.build_id' => '7b3803f0',
    'container.build_time' => 1714035003,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOhXnBO3');
