<?php

namespace ContainerOhXnBO3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9euCKWAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9euCKWA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9euCKWA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'security.event_dispatcher.authentication' => ['privates', 'security.event_dispatcher.authentication', 'getSecurity_EventDispatcher_AuthenticationService', false],
            'security.event_dispatcher.user' => ['privates', 'security.event_dispatcher.user', 'getSecurity_EventDispatcher_UserService', true],
        ], [
            'event_dispatcher' => '?',
            'security.event_dispatcher.authentication' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
            'security.event_dispatcher.user' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
        ]);
    }
}
