<?php

namespace ContainerOhXnBO3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\NoteController' shared autowired service.
     *
     * @return \App\Controller\NoteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/NoteController.php';

        $container->services['App\\Controller\\NoteController'] = $instance = new \App\Controller\NoteController(($container->privates['App\\Repository\\NoteRepository'] ?? $container->load('getNoteRepositoryService')), ($container->services['.container.private.serializer'] ?? $container->load('get_Container_Private_SerializerService')));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\NoteController', $container));

        return $instance;
    }
}
