<?php

namespace ContainerOhXnBO3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Logout_Listener_LegacySuccessListener_AuthenticationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.logout.listener.legacy_success_listener.authentication' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\LegacyLogoutHandlerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/LegacyLogoutHandlerListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Logout/LogoutSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/LogoutHandler.php';

        return $container->privates['security.logout.listener.legacy_success_listener.authentication'] = new \Symfony\Bundle\SecurityBundle\Security\LegacyLogoutHandlerListener(new \App\Security\LogoutHandler());
    }
}
